@startuml
skinparam defaultFontName メイリオ
skinparam monochrome true
skinparam shadowing false
skinparam RoundCorner 7
skinparam SequenceGroupBorderThickness 1
skinparam sequenceMessageAlign center
skinparam sequenceReferenceAlign left
skinparam NoteFontSize 9

participant "PC" as pc
participant "Server" as server

group TCP 3-way-handshake
  pc -> server: [tcp/80] SYN
  note over pc: SYN=1, ACK=0, SEQNUM=0
  server -> pc: [tcp/random] SYN + ACK
  note over server: SYN=1, ACK=1, SEQNUM=0, ACKNUM=1
  pc -> server: [tcp/80] ACK
  note over pc: SYN=0, ACK=1, SEQNUM=1, ACKNUM=1
end

...
pc <<-->> server: TCP session is established
...

group Terminate TCP session (TCP four wave)
  server -> pc: [tcp/80] FIN
  note over server
    ACK=1, FIN=1, SEQNUM=1678, ACKNUM=901
  end note
  pc -> server: [tcp/random] ACK
  note over pc: ACK=1, SEQNUM=901, ACKNUM=1679
  pc -> server: [tcp/random] FIN
  note over pc: ACK=1, FIN=1, SEQNUM=1679, ACKNUM=902
  server -> pc: [tcp/80] ACK
  note over server: ACK=1, SEQNUM=902, ACKNUM=1680
end

footer Copyright 2020 oresmalabo.net
@enduml