@startuml
skinparam defaultFontName メイリオ
skinparam monochrome true
skinparam shadowing false
skinparam RoundCorner 7
skinparam SequenceGroupBorderThickness 1
skinparam sequenceMessageAlign center
skinparam sequenceReferenceAlign left

participant DNS as dns
participant "PC(browser)" as pc
participant "Web-server" as server

group Domain name resolution
  pc -> dns : [udp/53] dns A query: www.example.com
  dns -> pc : [udp/random] dns A reply: 93.184.216.34
end

group TCP 3-way-handshake
  pc -> server: [tcp/80] SYN
  server -> pc: [tcp/random] SYN + ACK
  pc -> server: [tcp/80] ACK
end

group HTTP sequence
  pc -> server: GET /index.html HTTP/1.1
  note over pc
    GET / HTTP/1.1
    Host: www.example.com
    User-Agent: <user agent name>
    Accept: text/html
    Accept-Encoding: gzip
    Accept-Language: en-US
  end note
  server -> pc: HTTP/1.1 200 OK
  note over server
    HTTP/1.1 200 OK
    Content-Encoding: gzip
    ・
    ・
    ・
    Content-Length: 648
    
    <!doctype html>
    <html>
    <head>
        <title>Example Domain</title>
    ・
    ・
    ・
    </body>
    </html>
  end note
end

group Terminate TCP session (TCP four wave)
  server -> pc: [tcp/80] FIN
  note over server
  end note
  pc -> server: [tcp/random] ACK
  pc -> server: [tcp/random] FIN
  server -> pc: [tcp/80] ACK
end

footer Copyright 2020 oresmalabo.net
@enduml